# Match_Predictor_DNN_serieA_extended

This script loads the previously trained classifier and performs a prediction.

In [1]:
# Import the necessary libraries.
import pandas as pd
from pandas.tools.plotting import scatter_matrix
import numpy as np
from time import time
import tensorflow as tf
from sklearn.metrics import confusion_matrix
import itertools
from IPython.display import display

import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")
pd.options.mode.chained_assignment = None  # default='warn'



%matplotlib inline

In [2]:
data = pd.read_csv('../Datasets/serie_A/final_dataset_serieA_extended.csv')

N_MATCHES_TO_PREDICT = 10

classifierFilename = './models/football_classifier_serieA_DNN_extended'

## Assign penalty or boosting to the teams scores
This is done to consider the fact that the players might be tired or have a very high motivation

indx = data.index[(data.HomeTeam == 'Chievo') & (data.AwayTeam == 'Napoli')].tolist()[-1] # champions
data.AwayAttack[indx]   = data.AwayAttack[indx]*0.5
data.AwayMedium[indx]  = data.AwayMedium[indx]*0.5
data.AwayDefense[indx] = data.AwayDefense[indx]*0.5
data.AwayGK[indx]      = data.AwayGK[indx]

indx = data.index[(data.HomeTeam == 'Fiorentina') & (data.AwayTeam == 'Roma')].tolist()[-1] # champions
data.AwayAttack[indx]   = data.AwayAttack[indx]*0.5
data.AwayMedium[indx]  = data.AwayMedium[indx]*0.5
data.AwayDefense[indx] = data.AwayDefense[indx]*0.5
data.AwayGK[indx]      = data.AwayGK[indx]

indx = data.index[(data.HomeTeam == 'Juventus') & (data.AwayTeam == 'Benevento')].tolist()[-1] # champions
data.HomeAttack[indx]   = data.HomeAttack[indx]*0.5
data.HomeMedium[indx]  = data.HomeMedium[indx]*0.5
data.HomeDefense[indx] = data.HomeDefense[indx]*0.5
data.HomeGK[indx]      = data.HomeGK[indx]

indx = data.index[(data.HomeTeam == 'Sassuolo') & (data.AwayTeam == 'Milan')].tolist()[-1] # europa
data.AwayAttack[indx]   = data.AwayAttack[indx]*0.5
data.AwayMedium[indx]  = data.AwayMedium[indx]*0.5
data.AwayDefense[indx] = data.AwayDefense[indx]*0.5
data.AwayGK[indx]      = data.AwayGK[indx]

indx = data.index[(data.HomeTeam == 'Atalanta') & (data.AwayTeam == 'Spal')].tolist()[-1] # europa
data.HomeAttack[indx]   = data.HomeAttack[indx]*0.5
data.HomeMedium[indx]  = data.HomeMedium[indx]*0.5
data.HomeDefense[indx] = data.HomeDefense[indx]*0.5
data.HomeGK[indx]      = data.HomeGK[indx]

indx = data.index[(data.HomeTeam == 'Lazio') & (data.AwayTeam == 'Udinese')].tolist()[-1] # europa
data.HomeAttack[indx]   = data.HomeAttack[indx]*0.5
data.HomeMedium[indx]  = data.HomeMedium[indx]*0.5
data.HomeDefense[indx] = data.HomeDefense[indx]*0.5
data.HomeGK[indx]      = data.HomeGK[indx]

In [3]:
display(data.iloc[-N_MATCHES_TO_PREDICT:, :])

,Unnamed: 0,AC,AF,AM1,AM2,AM3,AM4,AR,AS,AST,...,HTLossStreak5,ATWinStreak3,ATWinStreak5,ATLossStreak3,ATLossStreak5,HTGD,ATGD,DiffPts,DiffFormPts,DiffLP
3158,3158,NaN,NaN,W,W,W,W,NaN,NaN,NaN,...,0,1,0,0,0,1.166667,1.583333,-0.083333,0.000000,1.0
3159,3159,NaN,NaN,L,W,D,L,NaN,NaN,NaN,...,0,0,0,0,0,2.000000,0.000000,1.250000,0.500000,-6.0
3160,3160,NaN,NaN,L,L,L,D,NaN,NaN,NaN,...,0,0,0,0,0,-0.923077,-0.692308,0.461538,0.384615,-3.0
3161,3161,NaN,NaN,L,L,L,W,NaN,NaN,NaN,...,0,0,0,0,0,-2.000000,-1.153846,-0.615385,-0.230769,3.0
3162,3162,NaN,NaN,W,W,W,W,NaN,NaN,NaN,...,0,1,0,0,0,0.846154,1.846154,-0.538462,-0.384615,4.0
3163,3163,NaN,NaN,L,L,W,W,NaN,NaN,NaN,...,0,0,0,0,0,-0.769231,0.307692,-0.538462,-0.153846,7.0
3164,3164,NaN,NaN,D,L,L,W,NaN,NaN,NaN,...,0,0,0,0,0,-0.153846,-0.384615,0.076923,0.000000,-3.0
3165,3165,NaN,NaN,W,L,W,L,NaN,NaN,NaN,...,0,0,0,0,0,-0.307692,-0.769231,0.076923,0.076923,-1.0
3166,3166,NaN,NaN,D,L,W,W,NaN,NaN,NaN,...,0,0,0,0,0,1.076923,0.230769,1.076923,0.076923,-7.0
3167,3167,NaN,NaN,L,L,L,L,NaN,NaN,NaN,...,0,0,0,1,0,-1.384615,-0.307692,-0.615385,0.000000,7.0

## Preparing the Data

In [4]:
# Remove first 3 matchweeks
data = data[data.MW > 3]

teams = pd.concat([data['Date'], data['HomeTeam'], data['AwayTeam']], axis=1, keys=['Date', 'HomeTeam', 'AwayTeam'])


data.drop(['Unnamed: 0','HomeTeam', 'AwayTeam','Date', 'MW', 'HTFormPtsStr', 'ATFormPtsStr', 'FTHG', 'FTAG',
           'HTGS', 'ATGS', 'HTGC', 'ATGC','HomeTeamLP', 'AwayTeamLP','DiffPts','HTFormPts','ATFormPts',
           'HM4','AM4','HTLossStreak5','ATLossStreak5','HTWinStreak5','ATWinStreak5',
           'HTWinStreak3','HTLossStreak3','ATWinStreak3','ATLossStreak3', 'ENTROPY_B365', 'ENTROPY_BW',
           'ENTROPY_IW', 'ENTROPY_LB', 'ENTROPY_WH', 'ENTROPY_H', 'ENTROPY_D', 'ENTROPY_A',
           'B365H', 'BWH', 'IWH', 'LBH', 'WHH', 'B365D', 'BWD', 'IWD', 'LBD', 'WHD', 'B365A', 'BWA', 'IWA',
           'LBA', 'WHA','PSA', 'PSCA', 'PSCD', 'PSCH', 'PSD', 'PSH', 'SBA', 'SBD', 'SBH', 'SJA', 'SJD',
           'SJH', 'VCA', 'VCD', 'VCH', 'GBA', 'GBD', 'GBH', 'HC', 'HF', 'AC', 'AF', 'BbAv<2.5', 'BbAv>2.5',
           'BbAvA', 'BbAvAHA', 'BbAvAHH', 'BbAvD', 'BbAvH', 'BbMx<2.5', 'BbMx>2.5', 'BbMxA', 'BbMxAHA', 'AY',
           'BbMxAHH', 'BbMxD', 'BbMxH', 'BbOU', 'Div', 'HR', 'HS', 'HST', 'HTAG', 'HTHG', 'AR', 'AS', 'AST',
           'BSA', 'BSD', 'BSH', 'Bb1X2', 'BbAH', 'BbAHh', 'HTR', 'HY',
           'HomeAttack', 'HomeMedium', 'HomeDefense', 'HomeGK', 'HomeAwayDifference',
           'AwayAttack', 'AwayMedium', 'AwayDefense', 'AwayGK','HomeScore_PrevW1', 'AwayScore_PrevW1'],1, inplace=True)

In [5]:
# Separate into feature set and target variable
X_all_raw = data.drop(['FTR'],1)
y_all_raw = data['FTR']

In [6]:
X_all_raw.HM1 = X_all_raw.HM1.astype('str')
X_all_raw.HM2 = X_all_raw.HM2.astype('str')
X_all_raw.HM3 = X_all_raw.HM3.astype('str')
X_all_raw.AM1 = X_all_raw.AM1.astype('str')
X_all_raw.AM2 = X_all_raw.AM2.astype('str')
X_all_raw.AM3 = X_all_raw.AM3.astype('str')

def preprocess_features(X):
    ''' Preprocesses the football data and converts catagorical variables into dummy variables. '''
    
    # Initialize new output DataFrame
    output = pd.DataFrame(index = X.index)

    # Investigate each feature column for the data
    for col, col_data in X.iteritems():

        # If data type is categorical, convert to dummy variables
        if col_data.dtype == object:
            col_data = pd.get_dummies(col_data, prefix = col)
                    
        # Collect the revised columns
        output = output.join(col_data)
    
    return output

def preprocess_labels(labels):
    labels =  pd.get_dummies(labels) # A [1, 0, 0] || D [0, 1, 0] || H [0, 0, 1]
    return labels


X_all_raw = preprocess_features(X_all_raw)
y_all_raw = preprocess_labels(y_all_raw)
print( "Processed feature columns ({} total features):\n{}".format(len(X_all_raw.columns), list(X_all_raw.columns)) )

Processed feature columns (26 total features):
['AM1_D', 'AM1_L', 'AM1_W', 'AM2_D', 'AM2_L', 'AM2_W', 'AM3_D', 'AM3_L', 'AM3_W', 'ATP', 'AwayScores', 'HM1_D', 'HM1_L', 'HM1_W', 'HM2_D', 'HM2_L', 'HM2_W', 'HM3_D', 'HM3_L', 'HM3_W', 'HTP', 'HomeScores', 'HTGD', 'ATGD', 'DiffFormPts', 'DiffLP']

In [7]:
# Standardising the data.
from sklearn.preprocessing import scale

cols = X_all_raw.keys().tolist()
#cols = ['HTGD','ATGD','HTP','ATP','DiffLP', 'HomeAttack', 'HomeMedium', 'HomeDefense', 'HomeGK', 'AwayAttack',
#       'AwayMedium', 'AwayDefense', 'HomeScores', 'AwayScores', 'HomeAwayDifference']
for col in cols:
    X_all_raw[col] = scale(X_all_raw[col])
    #X_all_raw[col] = X_all_raw[col]/max(X_all_raw[col])

In [8]:
# Show the feature information by printing the first five rows
print( "\nFeature values:" )
display(X_all_raw.head())

print( "\nLabels values:" )
display(y_all_raw.head())

Feature values:

,AM1_D,AM1_L,AM1_W,AM2_D,AM2_L,AM2_W,AM3_D,AM3_L,AM3_W,ATP,...,HM2_W,HM3_D,HM3_L,HM3_W,HTP,HomeScores,HTGD,ATGD,DiffFormPts,DiffLP
30,1.668319,-0.671697,-0.859332,-0.585585,1.181957,-0.697794,1.662419,-0.709854,-0.815206,-1.640655,...,1.194628,-0.582929,-0.824031,1.387198,2.053284,1.950517,1.944286,-0.788516,5.201054,-1.525026
31,-0.599406,-0.671697,1.163694,-0.585585,1.181957,-0.697794,1.662419,-0.709854,-0.815206,-0.590503,...,1.194628,-0.582929,1.213547,-0.720878,-1.080657,0.432882,-0.759023,-0.015288,-0.694921,-1.055089
32,-0.599406,1.488767,-0.859332,-0.585585,1.181957,-0.697794,-0.601533,1.408741,-0.815206,-2.690807,...,-0.837081,1.715476,-0.824031,-0.720878,-1.080657,1.083297,0.013351,-1.175131,2.253066,-0.937604
33,-0.599406,-0.671697,1.163694,-0.585585,-0.846054,1.433088,1.662419,-0.709854,-0.815206,0.984726,...,-0.837081,1.715476,-0.824031,-0.720878,-2.125304,-0.932989,-1.145210,2.304398,-4.379906,1.764535
34,-0.599406,1.488767,-0.859332,-0.585585,-0.846054,1.433088,-0.601533,-0.709854,1.226684,0.459650,...,-0.837081,-0.582929,1.213547,-0.720878,-2.647628,0.151036,-1.531397,-0.015288,-4.379906,0.119755

Labels values:

    A  D  H
30  0  0  1
31  0  1  0
32  0  0  1
33  1  0  0
34  0  1  0

# Separate training from test (i.e. to be predicted) data

In [9]:
X_test = X_all_raw.iloc[-N_MATCHES_TO_PREDICT:, :]
y_test = y_all_raw[-N_MATCHES_TO_PREDICT:]
ntest, _  = X_test.shape

print("Matches to predict: last %d"%( ntest))

test_dataset  = X_test.values.tolist()
test_labels   = y_test.values.tolist()

Matches to predict: last 10

## Aux functions

In [10]:
def decode_probabilities(y):
    labels = []
    for pred in y:
        max_val = max(pred)
        if pred[0] == max_val:
            labels.append('A')
        elif pred[1] == max_val:
            labels.append('D')
        elif pred[2] == max_val:
            labels.append('H')
    return labels

# Load the Deep Neural Network

In [11]:
y_pred = []

with tf.Session() as session:
    saver = tf.train.import_meta_graph(classifierFilename+'.meta')
    saver.restore(session, classifierFilename)

    tf.get_default_graph().as_graph_def()
    
    tf_test_dataset = session.graph.get_tensor_by_name("predict_dataset:0")
    test_prediction = session.graph.get_tensor_by_name("predict:0")

    for y in test_dataset:
        feed_dict = {tf_test_dataset : [y]}
        y_pred.append( list( session.run( [test_prediction], feed_dict=feed_dict)[0][0] ) )

INFO:tensorflow:Restoring parameters from ./models/football_classifier_serieA_DNN_extended

In [12]:
print(y_pred)

[[0.33521244, 0.66478759, 9.7845598e-10], [3.1309523e-21, 0.00048627838, 0.99951375], [0.12643765, 0.73014003, 0.14342238], [0.12643765, 0.73014003, 0.14342238], [0.00064296869, 0.96204269, 0.037314404], [0.27051747, 0.72948229, 2.3833059e-07], [1.996032e-05, 0.08398211, 0.91599792], [0.092772283, 0.56571573, 0.34151196], [7.6816151e-23, 0.00028581807, 0.9997142], [0.52144378, 0.47855619, 2.3439687e-28]]

In [13]:
teams_pred  = teams.iloc[-N_MATCHES_TO_PREDICT:, :]
teams_pred.index=teams_pred.index.tolist()

Pred_prob_A = []
Pred_prob_D = []
Pred_prob_H = []
for y in y_pred:
    Pred_prob_A.append(np.round(y[0], 3))
    Pred_prob_D.append(np.round(y[1], 3))
    Pred_prob_H.append(np.round(y[2], 3))

teams_pred['Predictions'] = decode_probabilities(y_pred)
teams_pred['Pred_prob_A'] = Pred_prob_A
teams_pred['Pred_prob_D'] = Pred_prob_D
teams_pred['Pred_prob_H'] = Pred_prob_H

teams_pred['Exact_res'] = decode_probabilities(test_labels)

In [14]:
display(teams_pred[['Date', 'HomeTeam','AwayTeam', 'Predictions', 'Pred_prob_H', 'Pred_prob_D', 'Pred_prob_A']])

,Date,HomeTeam,AwayTeam,Predictions,Pred_prob_H,Pred_prob_D,Pred_prob_A
3158,2017-11-17,Roma,Lazio,D,0.000,0.665,0.335
3159,2017-11-17,Napoli,Milan,H,1.000,0.000,0.000
3160,2017-11-18,Crotone,Genoa,D,0.143,0.730,0.126
3161,2017-11-18,Benevento,Sassuolo,D,0.143,0.730,0.126
3162,2017-11-18,Sampdoria,Juventus,D,0.037,0.962,0.001
3163,2017-11-18,Spal,Fiorentina,D,0.000,0.729,0.271
3164,2017-11-18,Torino,Chievo,H,0.916,0.084,0.000
3165,2017-11-18,Udinese,Cagliari,D,0.342,0.566,0.093
3166,2017-11-18,Inter,Atalanta,H,1.000,0.000,0.000
3167,2017-11-20,Verona,Bologna,A,0.000,0.479,0.521